In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [2]:
import pandas as pd

# Load your data into a DataFrame
data = pd.read_csv("/content/전세가격예측프로젝트_월별데이터_총병합.csv", encoding='euc-kr')

# Drop a specific column by name (replace 'column_to_drop' with the actual column name)
column_to_drop = 'IR'
data = data.drop(columns=[column_to_drop])

# Now 'column_to_drop' has been removed from the DataFrame 'data'
data

,Year,Month,Region_Name,Region_Code,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,...,JS_PPP,JS_Count,CR,CR_PPA,CR_PPP,UR,LC_index,CA_index,TC_index,SDT_index
0,2012,7,강남구,11680,단독다가구,316562.50,344.92,943.75,285.48,8,...,63.69,135,3.89,22.31,22.31,3.1,74.5,81.5,78.5,102.461258
1,2012,7,강남구,11680,아파트,82549.28,81.56,1023.00,309.46,133,...,136.96,750,46.13,44.26,44.26,3.1,74.5,81.5,78.5,102.461258
2,2012,7,강남구,11680,연립다세대,28362.79,48.58,565.35,171.02,38,...,105.95,140,61.63,61.95,61.95,3.1,74.5,81.5,78.5,102.461258
3,2012,7,강남구,11680,오피스텔,25309.88,39.07,671.99,203.28,42,...,127.79,10,157.65,62.87,62.86,3.1,74.5,81.5,78.5,102.461258
4,2012,7,강동구,11740,단독다가구,103757.14,336.59,480.88,145.47,21,...,49.10,217,7.61,33.75,33.75,3.1,74.5,81.5,78.5,102.461258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,11140,오피스텔,33270.39,29.85,1108.02,335.18,162,...,249.78,72,74.87,74.52,74.52,2.1,109.0,109.0,110.3,87.677816
12186,2022,8,중랑구,11260,단독다가구,113917.78,221.65,517.06,156.41,81,...,103.76,271,11.79,66.34,66.34,2.1,109.0,109.0,110.3,87.677816
12187,2022,8,중랑구,11260,아파트,54521.62,58.36,989.66,299.37,74,...,132.88,414,53.66,44.39,44.39,2.1,109.0,109.0,110.3,87.677816
12188,2022,8,중랑구,11260,연립다세대,33390.06,48.04,743.72,224.98,327,...,214.10,276,72.34,95.16,95.16,2.1,109.0,109.0,110.3,87.677816
12189,2022,8,중랑구,11260,오피스텔,12275.00,23.31,531.40,160.75,18,...,234.28,36,170.66,145.74,145.74,2.1,109.0,109.0,110.3,87.677816

In [3]:
import pandas as pd

data = pd.read_csv('/content/한국은행_기준금리(월별).csv', encoding='euc-kr')


# Create a DataFrame
df = pd.DataFrame(data)

# Split "통계표" into separate columns for Month and Year
df[['Month', 'Year']] = df['통계표'].str.split('-', expand=True)

# Drop the original "통계표" column
df = df.drop(columns=['통계표'])

# Display the DataFrame with Month and Year columns
print(df)

     1.3.1. 한국은행 기준금리 및 여수신금리 Month Year
0                        2.75   Jan   11
1                        2.75   Feb   11
2                        3.00   Mar   11
3                        3.00   Apr   11
4                        3.00   May   11
..                        ...   ...  ...
147                      3.50   Apr   23
148                      3.50   May   23
149                      3.50   Jun   23
150                      3.50   Jul   23
151                      3.50   Aug   23

[152 rows x 3 columns]

In [4]:
# Define a dictionary to map English month names to numbers
month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}

# Map the Month column to numerical values
df['Month'] = df['Month'].map(month_mapping)

# Display the DataFrame with Month and Year columns
print(df)

     1.3.1. 한국은행 기준금리 및 여수신금리  Month Year
0                        2.75      1   11
1                        2.75      2   11
2                        3.00      3   11
3                        3.00      4   11
4                        3.00      5   11
..                        ...    ...  ...
147                      3.50      4   23
148                      3.50      5   23
149                      3.50      6   23
150                      3.50      7   23
151                      3.50      8   23

[152 rows x 3 columns]

In [5]:
# Convert two-digit years to four-digit years
df['Year'] = '20' + df['Year']

print(df)

     1.3.1. 한국은행 기준금리 및 여수신금리  Month  Year
0                        2.75      1  2011
1                        2.75      2  2011
2                        3.00      3  2011
3                        3.00      4  2011
4                        3.00      5  2011
..                        ...    ...   ...
147                      3.50      4  2023
148                      3.50      5  2023
149                      3.50      6  2023
150                      3.50      7  2023
151                      3.50      8  2023

[152 rows x 3 columns]

In [6]:
df = df.rename(columns={'1.3.1. 한국은행 기준금리 및 여수신금리': 'IR'})
df

       IR  Month  Year
0    2.75      1  2011
1    2.75      2  2011
2    3.00      3  2011
3    3.00      4  2011
4    3.00      5  2011
..    ...    ...   ...
147  3.50      4  2023
148  3.50      5  2023
149  3.50      6  2023
150  3.50      7  2023
151  3.50      8  2023

[152 rows x 3 columns]

In [7]:
df.to_csv('한국은행_기준금리(월별)_converted.csv', index=False)

#### Panadas bug? IR data is divided into IR_x and IR_y, and truncates the decimal arbitrarliy.

In [8]:
import pandas as pd

# Read the original data from the CSV file
original_df = pd.read_csv('/content/전세가격예측프로젝트_월별데이터_총병합.csv', encoding='euc-kr')

# Read the IR data from the converted CSV file
ir_df = pd.read_csv('/content/한국은행_기준금리(월별)_converted.csv', encoding='utf-8')

# Merge the two DataFrames based on Year and Month
Total_Data = original_df.merge(ir_df[['Year', 'Month', 'IR']], on=['Year', 'Month'], how='left')

Total_Data = Total_Data.drop(columns=['IR_x'])

Total_Data = Total_Data.rename(columns={'IR_y': 'IR'})

print(Total_Data)

       Year  Month Region_Name  Region_Code Building_Use  Sell_Price  Sell_BA  \
0      2012      7         강남구        11680        단독다가구   316562.50   344.92
1      2012      7         강남구        11680          아파트    82549.28    81.56
2      2012      7         강남구        11680        연립다세대    28362.79    48.58
3      2012      7         강남구        11680         오피스텔    25309.88    39.07
4      2012      7         강동구        11740        단독다가구   103757.14   336.59
...     ...    ...         ...          ...          ...         ...      ...
12185  2022      8          중구        11140         오피스텔    33270.39    29.85
12186  2022      8         중랑구        11260        단독다가구   113917.78   221.65
12187  2022      8         중랑구        11260          아파트    54521.62    58.36
12188  2022      8         중랑구        11260        연립다세대    33390.06    48.04
12189  2022      8         중랑구        11260         오피스텔    12275.00    23.31

       Sell_PPA  Sell_PPP  Sell_Count  ...  JS_Count      CR  CR_PPA  CR_PPP  \
0        943.75    285.48           8  ...       135    3.89   22.31   22.31
1       1023.00    309.46         133  ...       750   46.13   44.26   44.26
2        565.35    171.02          38  ...       140   61.63   61.95   61.95
3        671.99    203.28          42  ...        10  157.65   62.87   62.86
4        480.88    145.47          21  ...       217    7.61   33.75   33.75
...         ...       ...         ...  ...       ...     ...     ...     ...
12185   1108.02    335.18         162  ...        72   74.87   74.52   74.52
12186    517.06    156.41          81  ...       271   11.79   66.34   66.34
12187    989.66    299.37          74  ...       414   53.66   44.39   44.39
12188    743.72    224.98         327  ...       276   72.34   95.16   95.16
12189    531.40    160.75          18  ...        36  170.66  145.74  145.74

        UR  LC_index  CA_index  TC_index   SDT_index   IR
0      3.1      74.5      81.5      78.5  102.461258  3.0
1      3.1      74.5      81.5      78.5  102.461258  3.0
2      3.1      74.5      81.5      78.5  102.461258  3.0
3      3.1      74.5      81.5      78.5  102.461258  3.0
4      3.1      74.5      81.5      78.5  102.461258  3.0
...    ...       ...       ...       ...         ...  ...
12185  2.1     109.0     109.0     110.3   87.677816  2.5
12186  2.1     109.0     109.0     110.3   87.677816  2.5
12187  2.1     109.0     109.0     110.3   87.677816  2.5
12188  2.1     109.0     109.0     110.3   87.677816  2.5
12189  2.1     109.0     109.0     110.3   87.677816  2.5

[12190 rows x 24 columns]

In [9]:
Total_Data.to_csv('Total_Data.csv', index=False)

In [10]:
import pandas as pd

total_df = pd.read_csv('/content/Total_Data.csv', encoding='utf-8')

crime_df = pd.read_csv('/content/서울시5대범죄전처리완료.csv', encoding='euc-kr')

crime_df = crime_df.rename(columns={'rates': 'Crime_Rates'})

Total_Data = total_df.merge(crime_df[['Year', 'Region_Name', 'Crime_Rates']], on=['Year', 'Region_Name'], how='left')

print(Total_Data)

       Year  Month Region_Name  Region_Code Building_Use  Sell_Price  Sell_BA  \
0      2012      7         강남구        11680        단독다가구   316562.50   344.92
1      2012      7         강남구        11680          아파트    82549.28    81.56
2      2012      7         강남구        11680        연립다세대    28362.79    48.58
3      2012      7         강남구        11680         오피스텔    25309.88    39.07
4      2012      7         강동구        11740        단독다가구   103757.14   336.59
...     ...    ...         ...          ...          ...         ...      ...
12185  2022      8          중구        11140         오피스텔    33270.39    29.85
12186  2022      8         중랑구        11260        단독다가구   113917.78   221.65
12187  2022      8         중랑구        11260          아파트    54521.62    58.36
12188  2022      8         중랑구        11260        연립다세대    33390.06    48.04
12189  2022      8         중랑구        11260         오피스텔    12275.00    23.31

       Sell_PPA  Sell_PPP  Sell_Count  ...      CR  CR_PPA  CR_PPP   UR  \
0        943.75    285.48           8  ...    3.89   22.31   22.31  3.1
1       1023.00    309.46         133  ...   46.13   44.26   44.26  3.1
2        565.35    171.02          38  ...   61.63   61.95   61.95  3.1
3        671.99    203.28          42  ...  157.65   62.87   62.86  3.1
4        480.88    145.47          21  ...    7.61   33.75   33.75  3.1
...         ...       ...         ...  ...     ...     ...     ...  ...
12185   1108.02    335.18         162  ...   74.87   74.52   74.52  2.1
12186    517.06    156.41          81  ...   11.79   66.34   66.34  2.1
12187    989.66    299.37          74  ...   53.66   44.39   44.39  2.1
12188    743.72    224.98         327  ...   72.34   95.16   95.16  2.1
12189    531.40    160.75          18  ...  170.66  145.74  145.74  2.1

       LC_index  CA_index  TC_index   SDT_index   IR  Crime_Rates
0          74.5      81.5      78.5  102.461258  3.0          NaN
1          74.5      81.5      78.5  102.461258  3.0          NaN
2          74.5      81.5      78.5  102.461258  3.0          NaN
3          74.5      81.5      78.5  102.461258  3.0          NaN
4          74.5      81.5      78.5  102.461258  3.0          NaN
...         ...       ...       ...         ...  ...          ...
12185     109.0     109.0     110.3   87.677816  2.5          NaN
12186     109.0     109.0     110.3   87.677816  2.5          NaN
12187     109.0     109.0     110.3   87.677816  2.5          NaN
12188     109.0     109.0     110.3   87.677816  2.5          NaN
12189     109.0     109.0     110.3   87.677816  2.5          NaN

[12190 rows x 25 columns]

In [11]:
Total_Data.to_csv('Total_Data.csv', index=False)

## Preprocessing of missing values using Regression Imputation

In [12]:
import pandas as pd
from sklearn.linear_model import LinearRegression


# Create a subset of data with non-missing values in predictor and target variables
train_data = Total_Data.dropna(subset=['Year', 'Crime_Rates'])

# Separate predictor and target variables in the training set
X_train = train_data[['Year']]
y_train = train_data['Crime_Rates']

# Fit a regression model on the training data
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)

# Predict missing values using the trained model
X_missing = Total_Data.loc[Total_Data['Crime_Rates'].isnull(), ['Year']]
predicted_values = regression_model.predict(X_missing)

# Fill in missing values with predicted values
Total_Data.loc[Total_Data['Crime_Rates'].isnull(), 'Crime_Rates'] = predicted_values

In [13]:
Total_Data.to_csv('Total_Data.csv', index=False)

In [14]:
df_pop = pd.read_csv("/content/서울_연령별_인구수_전처리.csv", encoding='utf-8')

df_pop = df_pop.rename(columns={'시점': 'Year', '행정구역(시군구)별': 'Region_Name', '계': 'Total_Pop'})

df_pop

     Year Region_Name  Total_Pop  0 - 19세  20 - 34세  35 - 54세     55 -
0    2000       서울특별시   10287787  2749537   3071339   3097026  1369884
1    2000         종로구     186484    44708     54219     54308    33248
2    2000          중구     133632    30770     40371     38671    23819
3    2000         용산구     238788    55423     72768     68443    42153
4    2000         성동구     339982    87422    107141     97142    48277
..    ...         ...        ...      ...       ...       ...      ...
593  2022         관악구     482092    45580    160220    132614   143678
594  2022         서초구     402936    74666     78948    137669   111652
595  2022         강남구     522782    92825    106792    179369   143796
596  2022         송파구     652993   105061    141710    212117   194105
597  2022         강동구     457679    72267     93573    146005   145833

[598 rows x 7 columns]

In [15]:
df_pop.to_csv('Total_Pop_Preprocessed.csv', index=False)

In [16]:
Total_Data = Total_Data.merge(df_pop[['Year', 'Region_Name', 'Total_Pop']], on=['Year', 'Region_Name'], how='left')

print(Total_Data)

       Year  Month Region_Name  Region_Code Building_Use  Sell_Price  Sell_BA  \
0      2012      7         강남구        11680        단독다가구   316562.50   344.92
1      2012      7         강남구        11680          아파트    82549.28    81.56
2      2012      7         강남구        11680        연립다세대    28362.79    48.58
3      2012      7         강남구        11680         오피스텔    25309.88    39.07
4      2012      7         강동구        11740        단독다가구   103757.14   336.59
...     ...    ...         ...          ...          ...         ...      ...
12185  2022      8          중구        11140         오피스텔    33270.39    29.85
12186  2022      8         중랑구        11260        단독다가구   113917.78   221.65
12187  2022      8         중랑구        11260          아파트    54521.62    58.36
12188  2022      8         중랑구        11260        연립다세대    33390.06    48.04
12189  2022      8         중랑구        11260         오피스텔    12275.00    23.31

       Sell_PPA  Sell_PPP  Sell_Count  ...  CR_PPA  CR_PPP   UR  LC_index  \
0        943.75    285.48           8  ...   22.31   22.31  3.1      74.5
1       1023.00    309.46         133  ...   44.26   44.26  3.1      74.5
2        565.35    171.02          38  ...   61.95   61.95  3.1      74.5
3        671.99    203.28          42  ...   62.87   62.86  3.1      74.5
4        480.88    145.47          21  ...   33.75   33.75  3.1      74.5
...         ...       ...         ...  ...     ...     ...  ...       ...
12185   1108.02    335.18         162  ...   74.52   74.52  2.1     109.0
12186    517.06    156.41          81  ...   66.34   66.34  2.1     109.0
12187    989.66    299.37          74  ...   44.39   44.39  2.1     109.0
12188    743.72    224.98         327  ...   95.16   95.16  2.1     109.0
12189    531.40    160.75          18  ...  145.74  145.74  2.1     109.0

       CA_index  TC_index   SDT_index   IR  Crime_Rates  Total_Pop
0          81.5      78.5  102.461258  3.0     1.548846     554870
1          81.5      78.5  102.461258  3.0     1.548846     554870
2          81.5      78.5  102.461258  3.0     1.548846     554870
3          81.5      78.5  102.461258  3.0     1.548846     554870
4          81.5      78.5  102.461258  3.0     1.548846     484742
...         ...       ...         ...  ...          ...        ...
12185     109.0     110.3   87.677816  2.5     0.865139     119206
12186     109.0     110.3   87.677816  2.5     0.865139     383496
12187     109.0     110.3   87.677816  2.5     0.865139     383496
12188     109.0     110.3   87.677816  2.5     0.865139     383496
12189     109.0     110.3   87.677816  2.5     0.865139     383496

[12190 rows x 26 columns]

In [17]:
Total_Data.to_csv('Total_Data.csv', index=False)

In [18]:
Total_Data = Total_Data.drop(columns=['Region_Code', 'CR_PPA', 'CR_PPP'])
Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,JS_Count,CR,UR,LC_index,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,135,3.89,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,750,46.13,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,140,61.63,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,10,157.65,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,217,7.61,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,484742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,72,74.87,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,119206
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,271,11.79,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,414,53.66,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,276,72.34,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,36,170.66,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496

In [19]:
df_subway = pd.read_csv("/content/지하철_전처리.csv", encoding='euc-kr')


df_subway['Region_Name'] = df_subway['구주소'].str.extract(r'(\S+구)')

df_subway

,호선,역명,구주소,도로명주소,위도,경도,Region_Name
0,2호선,봉천,서울특별시 관악구 봉천동 979-7 봉천역(2호선),서울특별시 관악구 남부순환로 지하1721(봉천동),37.487812,126.957234,관악구
1,1호선,서울,서울특별시 중구 남대문로5가 73-6 서울역(1호선),서울특별시 중구 세종대로 지하2(남대문로 5가),37.558735,126.973859,중구
2,1호선,시청,서울특별시 중구 정동 5-5 시청역(1호선),서울특별시 중구 세종대로 지하101(정동),37.566608,126.973148,중구
3,1호선,종각,서울특별시 종로구 종로1가 54 종각역(1호선),서울특별시 종로구 종로 지하55(종로1가),37.570011,126.982108,종로구
4,1호선,종로3가,서울특별시 종로구 종로3가 10-5 종로3가역(1호선),서울특별시 종로구 종로 지하129(종로3가),37.570447,126.990896,종로구
...,...,...,...,...,...,...,...
268,9호선,송파나루,서울특별시 송파구 방이동 2 송파나루역(9호선),서울특별시 송파구 백제고분로 지하446(방이동),37.511169,127.095426,송파구
269,9호선,한성백제,서울특별시 송파구 방이동 88-17 한성백제역(9호선),서울특별시 송파구 위례성대로 지하29(방이동),37.510952,127.129178,송파구
270,9호선,올림픽공원(한국체대),서울특별시 송파구 방이동 89-28 올림픽공원역(9호선),서울특별시 송파구 양재대로 지하1233(방이동),37.511246,127.129362,송파구
271,9호선,둔촌오륜,서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선),서울특별시 강동구 강동대로 지하303(둔촌동),37.522146,127.133775,강동구
272,9호선,중앙보훈병원,서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선),서울특별시 강동구 동남로 지하625(둔촌동),37.534876,127.145270,강동구

In [20]:
df_subway.to_csv('Subway_Stations.csv', encoding = 'utf-8', index=False)

In [21]:
df_school = pd.read_csv("/content/초,중,고등학교_전처리.csv", encoding='euc-kr')


df_school['Region_Name'] = df_school['소재지도로명주소'].str.extract(r'(\S+구)')

df_school

,학교명,학교급구분,소재지도로명주소,위도,경도,Region_Name
0,서울영림초등학교,초등학교,서울특별시 영등포구 시흥대로173길 14 . 서울영림초등학교 (대림동),37.487298,126.902539,영등포구
1,서울평화초등학교,초등학교,서울특별시 송파구 송파대로26길 22 . 서울평화초등학교 (가락동),37.491629,127.122357,송파구
2,서울양동초등학교,초등학교,서울특별시 양천구 오목로23길 24 (신정동),37.526006,126.851159,양천구
3,서울중화초등학교,초등학교,서울특별시 중랑구 신내로7가길 22 . 서울중화초등학교 (신내동),37.603003,127.094649,중랑구
4,서울상월초등학교,초등학교,서울특별시 노원구 동일로221길 27 (상계동),37.658487,127.057172,노원구
...,...,...,...,...,...,...
1308,환일고등학교,고등학교,서울특별시 중구 환일길 47 (만리동2가),37.553868,126.961870,중구
1309,금호고등학교,고등학교,서울특별시 성동구 금호로 118 (금호동1가. 금호고등학교),37.553325,127.023906,성동구
1310,도선고등학교,고등학교,서울특별시 성동구 마장로 156 (하왕십리동),37.566656,127.027029,성동구
1311,대진여자고등학교,고등학교,서울특별시 노원구 공릉로 438 . 대진여자고등학교 (중계동),37.646174,127.067324,노원구
1312,서울인공지능고등학교,고등학교,서울특별시 송파구 양산로 21 (거여동),37.491753,127.142461,송파구

In [22]:
df_school.to_csv('School.csv', encoding = 'utf-8', index=False)

In [23]:
df_parks = pd.read_csv("/content/Parks.csv", encoding='euc-kr')
df_university = pd.read_csv("/content/University.csv", encoding='euc-kr')

In [24]:
############### df_university df_parks df_school df_subway #################

# Step 1: Calculate the total number for each unique Region_Name
Univ_Counts = df_university['Region_Name'].value_counts().reset_index()
Univ_Counts.columns = ['Region_Name', 'Univ_Counts']

# Step 2: Merge the counts with Total_Data based on the common "Region_Name" column
Total_Data = Total_Data.merge(Univ_Counts, on='Region_Name', how='left')

Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,CR,UR,LC_index,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop,Univ_Counts
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,3.89,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,46.13,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,61.63,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,157.65,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,7.61,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,484742,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,74.87,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,119206,2.0
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,11.79,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,53.66,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,72.34,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,170.66,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0

In [25]:
############### df_university df_parks df_school df_subway #################

# Step 1: Calculate the total number of schools for each unique Region_Name
Park_Counts = df_parks['Region_Name'].value_counts().reset_index()
Park_Counts.columns = ['Region_Name', 'Park_Counts']

# Step 2: Merge the school counts with Total_Data based on the common "Region_Name" column
Total_Data = Total_Data.merge(Park_Counts, on='Region_Name', how='left')

Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,UR,LC_index,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop,Univ_Counts,Park_Counts
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,3.1,74.5,81.5,78.5,102.461258,3.0,1.548846,484742,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,119206,2.0,4
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,2.1,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6

In [26]:
############### df_university df_parks df_school df_subway #################

# Step 1: Calculate the total number of schools for each unique Region_Name
School_Counts = df_school['Region_Name'].value_counts().reset_index()
School_Counts.columns = ['Region_Name', 'School_Counts']

# Step 2: Merge the school counts with Total_Data based on the common "Region_Name" column
Total_Data = Total_Data.merge(School_Counts, on='Region_Name', how='left')

Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,LC_index,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop,Univ_Counts,Park_Counts,School_Counts
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,74.5,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,74.5,81.5,78.5,102.461258,3.0,1.548846,484742,NaN,7,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,109.0,109.0,110.3,87.677816,2.5,0.865139,119206,2.0,4,31
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,109.0,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48

In [27]:
############### df_university df_parks df_school df_subway #################

# Step 1: Calculate the total number of schools for each unique Region_Name
Subway_Counts = df_subway['Region_Name'].value_counts().reset_index()
Subway_Counts.columns = ['Region_Name', 'Subway_Counts']

# Step 2: Merge the school counts with Total_Data based on the common "Region_Name" column
Total_Data = Total_Data.merge(Subway_Counts, on='Region_Name', how='left')

Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop,Univ_Counts,Park_Counts,School_Counts,Subway_Counts
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,81.5,78.5,102.461258,3.0,1.548846,484742,NaN,7,60,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,109.0,110.3,87.677816,2.5,0.865139,119206,2.0,4,31,23
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8

In [32]:
Total_Data = Total_Data.fillna(0)
Total_Data

,Year,Month,Region_Name,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,JS_Price,...,CA_index,TC_index,SDT_index,IR,Crime_Rates,Total_Pop,Univ_Counts,Park_Counts,School_Counts,Subway_Counts
0,2012,7,강남구,단독다가구,316562.50,344.92,943.75,285.48,8,12301.48,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
1,2012,7,강남구,아파트,82549.28,81.56,1023.00,309.46,133,38076.56,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
2,2012,7,강남구,연립다세대,28362.79,48.58,565.35,171.02,38,17478.57,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
3,2012,7,강남구,오피스텔,25309.88,39.07,671.99,203.28,42,39900.00,...,81.5,78.5,102.461258,3.0,1.548846,554870,1.0,7,77,21
4,2012,7,강동구,단독다가구,103757.14,336.59,480.88,145.47,21,7899.77,...,81.5,78.5,102.461258,3.0,1.548846,484742,0.0,7,60,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,오피스텔,33270.39,29.85,1108.02,335.18,162,24908.53,...,109.0,110.3,87.677816,2.5,0.865139,119206,2.0,4,31,23
12186,2022,8,중랑구,단독다가구,113917.78,221.65,517.06,156.41,81,13429.04,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12187,2022,8,중랑구,아파트,54521.62,58.36,989.66,299.37,74,29258.90,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12188,2022,8,중랑구,연립다세대,33390.06,48.04,743.72,224.98,327,24155.01,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8
12189,2022,8,중랑구,오피스텔,12275.00,23.31,531.40,160.75,18,20947.92,...,109.0,110.3,87.677816,2.5,0.865139,383496,1.0,6,48,8

In [33]:
Total_Data.to_csv('Total_Data.csv', encoding='utf-8', index=False)

In [36]:
Total_APT = Total_Data[Total_Data['Building_Use'] == '아파트']
Total_Officetel = Total_Data[Total_Data['Building_Use'] == '오피스텔']
Total_Single_Family = Total_Data[Total_Data['Building_Use'] == '단독다가구']
Total_Townhouse = Total_Data[Total_Data['Building_Use'] == '연립다세대']

In [37]:
Total_APT.to_csv('Total_APT.csv', encoding='utf-8', index=False)
Total_Officetel.to_csv('Total_Officetel.csv', encoding='utf-8', index=False)
Total_Single_Family.to_csv('Total_Single_Family.csv', encoding='utf-8', index=False)
Total_Townhouse.to_csv('Total_Townhouse.csv', encoding='utf-8', index=False)

In [38]:
Total_APT_for_Target_Features = Total_APT.drop(columns=['Year', 'Month', 'Region_Name', 'Building_Use', 'Sell_PPA', 'Sell_PPP', 'Sell_BA', 'JS_BA', 'JS_PPA', 'JS_PPP'])
Total_Officetel_for_Target_Features = Total_Officetel.drop(columns=['Year', 'Month', 'Region_Name', 'Building_Use', 'Sell_PPA', 'Sell_PPP', 'Sell_BA', 'JS_BA', 'JS_PPA', 'JS_PPP'])
Total_Single_Family_for_Target_Features = Total_Single_Family.drop(columns=['Year', 'Month', 'Region_Name', 'Building_Use', 'Sell_PPA', 'Sell_PPP', 'Sell_BA', 'JS_BA', 'JS_PPA', 'JS_PPP'])
Total_Townhouse_for_Target_Features = Total_Townhouse.drop(columns=['Year', 'Month', 'Region_Name', 'Building_Use', 'Sell_PPA', 'Sell_PPP', 'Sell_BA', 'JS_BA', 'JS_PPA', 'JS_PPP'])

In [40]:
Total_APT_for_Target_Features.to_csv('Total_APT_for_Target_Features.csv', encoding='utf-8', index=False)
Total_Officetel_for_Target_Features.to_csv('Total_Officetel_for_Target_Features.csv', encoding='utf-8', index=False)
Total_Single_Family_for_Target_Features.to_csv('Total_Single_Family_for_Target_Features.csv', encoding='utf-8', index=False)
Total_Townhouse_for_Target_Features.to_csv('Total_Townhouse_for_Target_Features.csv', encoding='utf-8', index=False)